### ISSUE TITLE
DeprecationWarning

### ISSUE THREAD

**Issue by jacorachan** [nodeca/fs-tools#22]
https://github.com/nodeca/fs-tools/blob/3f0b9c2791e8e25b4ac019e472feba99fb412338/lib/fs-tools.js#L681

_[DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead._

This removes the warning:
```javascript
os.tmpdir ? os.tmpdir() : '/tmp',
```

**Comment by puzrin** [comment]
https://github.com/nodeca/fs-tools#fs-tools

This package is not supported anymore. I strongly recommend migrate to alternatives.
